name: Build Images

on:
  push:
    branches:
      - main
    paths:
      - "**/Dockerfile"
      - ".github/workflows/build.yaml"

env:
  IMAGE_PREFIX: loftsh

jobs:
  dotnet:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=5.0
        working-directory: ./dotnet
  go:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=1.16-alpine
          devspace build --var TAG=1.15-alpine
        working-directory: ./go
  java-gradle:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=7.0-jdk11
          devspace build --var TAG=7.0-jdk8
        working-directory: ./java-gradle
  java-maven:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=3-jdk-11
          devspace build --var TAG=3-jdk-8
        working-directory: ./java-maven
  javascript:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=15-alpine
          devspace build --var TAG=14-alpine
          devspace build --var TAG=12-alpine
          devspace build --var TAG=10-alpine
        working-directory: ./javascript
  php:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=8.0-apache
          devspace build --var TAG=8.0-fpm
          devspace build --var TAG=7.4-apache
          devspace build --var TAG=7.4-fpm
          devspace build --var TAG=7.3-apache
          devspace build --var TAG=7.3-fpm
        working-directory: ./php
  python:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=3.9-alpine
          devspace build --var TAG=3.8-alpine
          devspace build --var TAG=3.7-alpine
        working-directory: ./python
  ruby:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=3.0-alpine
          devspace build --var TAG=2.6-alpine
          devspace build --var TAG=2.5-alpine
        working-directory: ./ruby
  typescript:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=15-alpine
          devspace build --var TAG=14-alpine
          devspace build --var TAG=12-alpine
          devspace build --var TAG=10-alpine
        working-directory: ./typescript
