name: Build .NET

on:
  push:
    branches:
      - main
    paths:
      - "dotnet/**"
      - ".github/workflows/dotnet.yaml"
      - "install_tooling.sh"

env:
  IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}

jobs:
  dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Install DevSpace
        uses: loft-sh/setup-devspace@main
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=6.0-alpine
          devspace build --var TAG=5.0-alpine
          devspace build --var TAG=3.1-alpine
        working-directory: ./dotnet

