name: Build .NET

on:
  push:
    branches:
      - main
    paths:
      - "dotnet/**"
      - ".github/workflows/dotnet.yaml"
      - "install_tooling.sh"
  workflow_call:
    secrets:
      IMAGE_PREFIX:
        description: "registry.com/loftsh in registry.com/loftsh/language:TAG"
        required: true

env:
  IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
  LANGUAGE: "dotnet"

defaults:
  run:
    working-directory: dotnet

jobs:
  dotnet:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: 6.0-alpine
            target_tag: latest
          - tag: 6.0-alpine
            target_tag: 6.0-alpine
          - tag: 5.0-bullseye-slim
            target_tag: 5.0-bullseye-slim

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - uses: loft-sh/setup-devspace@main
      - run: devspace build --var TAG=${{ matrix.tag }} --var TARGET_TAG=${{ matrix.target_tag }}
