name: Build Go

on:
  push:
    branches:
      - main
    paths:
      - "go/**"
      - ".github/workflows/go.yaml"
      - "install_tooling.sh"
  workflow_call:
    secrets:
      IMAGE_PREFIX:
        description: "registry.com/loftsh in registry.com/loftsh/language:TAG"
        required: true

env:
  IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
  LANGUAGE: "go"

defaults:
  run:
    working-directory: go

jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: 1.17-alpine
            target_tag: latest
          - tag: 1.17-alpine
            target_tag: 1.17-alpine
          - tag: 1.16-alpine
            target_tag: 1.16-alpine
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - uses: loft-sh/setup-devspace@main
      - run: devspace build --var TAG=${{ matrix.tag }} --var TARGET_TAG=${{ matrix.target_tag }}
