name: Build Java (maven)

on:
  push:
    branches:
      - main
    paths:
      - "java-maven/**"
      - ".github/workflows/java-maven.yaml"
      - "install_tooling.sh"

env:
  IMAGE_PREFIX: loftsh

jobs:
  java-maven:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: chmod +x install_tooling.sh && sudo ./install_tooling.sh
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=3-jdk-11
          devspace build --var TAG=3-jdk-8
        working-directory: ./java-maven

