name: Build Java (gradle)

on:
  push:
    branches:
      - main
    paths:
      - "java-gradle/**"
      - ".github/workflows/java-gradle.yaml"
      - "install_tooling.sh"

env:
  IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}

jobs:
  java-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Install DevSpace
        uses: loft-sh/setup-devspace@main
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=7-jdk11
          devspace build --var TAG=7-jdk17
          devspace build --var TAG=6-jdk11
          devspace build --var TAG=6-jdk17
        working-directory: ./java-gradle

