name: Build Java (gradle)

on:
  push:
    branches:
      - main
    paths:
      - "java-gradle/**"
      - ".github/workflows/java-gradle.yaml"
      - "install_tooling.sh"
  workflow_call:
    secrets:
      IMAGE_PREFIX:
        description: "registry.com/loftsh in registry.com/loftsh/language:TAG"
        required: true

env:
  IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
  LANGUAGE: "java-gradle"

defaults:
  run:
    working-directory: java-gradle

jobs:
  java-gradle:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: latest
            target_tag: latest
          - tag: 7-jdk17
            target_tag: 7-jdk17
          - tag: 7-jdk11
            target_tag: 7-jdk11
          - tag: 6-jdk17
            target_tag: 6-jdk17
          - tag: 6-jdk11
            target_tag: 6-jdk11
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - uses: loft-sh/setup-devspace@main
      - run: devspace build --var TAG=${{ matrix.tag }} --var TARGET_TAG=${{ matrix.target_tag }}
