name: Build PHP

on:
  push:
    branches:
      - main
    paths:
      - "php/**"
      - ".github/workflows/php.yaml"
      - "install_tooling.sh"

env:
  IMAGE_PREFIX: loftsh

jobs:
  php:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: chmod +x install_tooling.sh && sudo ./install_tooling.sh
      - run: |
          devspace build --var TAG=latest
          devspace build --var TAG=8.0-apache
          devspace build --var TAG=8.0-fpm
          devspace build --var TAG=7.4-apache
          devspace build --var TAG=7.4-fpm
          devspace build --var TAG=7.3-apache
          devspace build --var TAG=7.3-fpm
        working-directory: ./php

