name: Build PHP

on:
  push:
    branches:
      - main
    paths:
      - "php/**"
      - ".github/workflows/php.yaml"
      - "install_tooling.sh"
  workflow_call:
    secrets:
      IMAGE_PREFIX:
        description: "registry.com/loftsh in registry.com/loftsh/language:TAG"
        required: true

env:
  IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
  LANGUAGE: "php"

defaults:
  run:
    working-directory: php

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: 8-apache-bullseye
            target_tag: latest
          - tag: 8-apache-bullseye
            target_tag: latest-apache
          - tag: 8.1-apache-bullseye
            target_tag: 8.1-apache-bullseye
          - tag: 8.0-apache-bullseye
            target_tag: 8.0-apache-bullseye
          - tag: 7-apache-bullseye
            target_tag: 7-apache-bullseye
          - tag: 8-fpm
            target_tag: latest-fpm 
          - tag: 8-fpm
            target_tag: 8-fpm
          - tag: 7-fpm
            target_tag: 7-fpm
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - uses: loft-sh/setup-devspace@main
      - run: devspace build --var TAG=${{ matrix.tag }} --var TARGET_TAG=${{ matrix.target_tag }}

