name: Build Python

on:
  push:
    branches:
      - main
    paths:
      - "python/**"
      - ".github/workflows/python.yaml"
      - "install_tooling.sh"
  workflow_call:
    secrets:
      IMAGE_PREFIX:
        description: "registry.com/loftsh in registry.com/loftsh/language:TAG"
        required: true

env:
  IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
  LANGUAGE: "python"

defaults:
  run:
    working-directory: python

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: 3-alpine
            target_tag: latest
          - tag: 3-alpine
            target_tag: 3-alpine
          - tag: 3.10-alpine
            target_tag: 3.10-alpine
          - tag: 3.9-alpine
            target_tag: 3.9-alpine
          - tag: 3.8-alpine
            target_tag: 3.8-alpine

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - uses: loft-sh/setup-devspace@main
      - run: devspace build --var TAG=${{ matrix.tag }} --var TARGET_TAG=${{ matrix.target_tag }}
