name: Build Ruby

on:
  push:
    branches:
      - main
    paths:
      - "ruby/**"
      - ".github/workflows/ruby.yaml"
      - "install_tooling.sh"

env:
  IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}

jobs:
  ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Install DevSpace
        uses: loft-sh/setup-devspace@main
      - run: |
          devspace build --var TAG=3.0.2 --var TARGET_TAG=latest
          devspace build --var TAG=3.0-alpine --var TARGET_TAG=3.0-alpine
          devspace build --var TAG=2.6-alpine --var TARGET_TAG=2.6-alpine
          devspace build --var TAG=2.5-alpine --var TARGET_TAG=2.5-alpine
        working-directory: ./ruby

